name: 'Daily email'

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Run task
        run: bash ./task.sh

      - name: Send mail
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.qq.com
          server_port: 465
          username: ${{ secrets.MAILUSERNAME }}
          password: ${{ secrets.MAILPASSWORD }}
          subject: Daily email:2020 夏令营信息
          body: file://result.html
          to: hemengmeng2017@outlook.com
          from: Dailyemail:hemengjie
          content_type: text/html

      - name: Commit files
        run: |
          git config --local user.email "njtech_hemengjie@qq.com"
          git config --local user.name "hemengjie in dailyemail"
          git add -A
          git commit -m "Add changes" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUBTOKEN }}

          